prefix cv: <http://vision.semkg.org/onto/v0.1/>

SELECT DISTINCT ?annotation
{
    ?annotation a cv:Annotation.
    ?annotation cv:hasAnnotatedObject ?cat.
    ?cat cv:hasId ?catId.
    ?cat cv:hasLabel ?label.
    FILTER (?label = "car")
}
LIMIT 2
