prefix cv: <http://vision.semkg.org/onto/v0.1/>

SELECT ?image ?annotation ?catId
{
    {
        SELECT ?image ?annotation ?catId
        {

        ?annotation a cv:Annotation.
        ?annotation cv:isAnnotationOfImage ?image.
        ?annotation cv:hasAnnotatedObject ?cat.
        ?cat cv:hasId ?catId.
        ?cat cv:hasLabel ?label.
        FILTER (?label = "car")

        }
        LIMIT 100
    }

    UNION {

        SELECT ?image ?annotation ?catId
        {

        ?annotation a cv:Annotation.
        ?annotation cv:isAnnotationOfImage ?image.
        ?annotation cv:hasAnnotatedObject ?cat.
        ?cat cv:hasId ?catId.
        ?cat cv:hasLabel ?label.
        FILTER (?label = "truck")

        }
        LIMIT 100
    }

    UNION {

        SELECT ?image ?annotation ?catId
        {

        ?annotation a cv:Annotation.
        ?annotation cv:isAnnotationOfImage ?image.
        ?annotation cv:hasAnnotatedObject ?cat.
        ?cat cv:hasId ?catId.
        ?cat cv:hasLabel ?label.
        FILTER (?label = "dog")

        }
        LIMIT 100
    }

    UNION {

        SELECT ?image ?annotation ?catId
        {

        ?annotation a cv:Annotation.
        ?annotation cv:isAnnotationOfImage ?image.
        ?annotation cv:hasAnnotatedObject ?cat.
        ?cat cv:hasId ?catId.
        ?cat cv:hasLabel ?label.
        FILTER (?label = "cat")

        }
        LIMIT 100
    }

    UNION {

        SELECT ?image ?annotation ?catId
        {

        ?annotation a cv:Annotation.
        ?annotation cv:isAnnotationOfImage ?image.
        ?annotation cv:hasAnnotatedObject ?cat.
        ?cat cv:hasId ?catId.
        ?cat cv:hasLabel ?label.
        FILTER (?label = "boat")

        }
        LIMIT 100
    }

    UNION {

        SELECT ?image ?annotation ?catId
        {

        ?annotation a cv:Annotation.
        ?annotation cv:isAnnotationOfImage ?image.
        ?annotation cv:hasAnnotatedObject ?cat.
        ?cat cv:hasId ?catId.
        ?cat cv:hasLabel ?label.
        FILTER (?label = "zebra")

        }
        LIMIT 100
    }

    UNION {

        SELECT ?image ?annotation ?catId
        {

        ?annotation a cv:Annotation.
        ?annotation cv:isAnnotationOfImage ?image.
        ?annotation cv:hasAnnotatedObject ?cat.
        ?cat cv:hasId ?catId.
        ?cat cv:hasLabel ?label.
        FILTER (?label = "horse")

        }
        LIMIT 100
    }

    UNION {

        SELECT ?image ?annotation ?catId
        {

        ?annotation a cv:Annotation.
        ?annotation cv:isAnnotationOfImage ?image.
        ?annotation cv:hasAnnotatedObject ?cat.
        ?cat cv:hasId ?catId.
        ?cat cv:hasLabel ?label.
        FILTER (?label = "elephant")

        }
        LIMIT 100
    }

    UNION {

        SELECT ?image ?annotation ?catId
        {

        ?annotation a cv:Annotation.
        ?annotation cv:isAnnotationOfImage ?image.
        ?annotation cv:hasAnnotatedObject ?cat.
        ?cat cv:hasId ?catId.
        ?cat cv:hasLabel ?label.
        FILTER (?label = "cow")

        }
        LIMIT 100
    }
}