prefix cv: <http://vision.semkg.org/onto/v0.1/>

SELECT ?x ?y ?w ?h ?label 
{
    ?annotation cv:isAnnotationOfImage ?image .
    ?annotation cv:hasBox ?box .
    ?box cv:centerX ?x .
    ?box cv:centerY ?y .
    ?box cv:hasWidth ?w .
    ?box cv:hasHeight ?h .
    ?annotation cv:hasAnnotatedObject ?cat .
    ?cat cv:hasLabel ?label .
}